[[Graphviz]]
arch = "aarch64"
git-tree-sha1 = "a139010dda067b4970a3d2c90cb05fe3659defe7"
os = "macos"

    [[Graphviz.download]]
    sha256 = "360c88a39ad84b9419c6a03fbfd6d5e2ec6a9cb57df84f71bc1a0b143a2f2f76"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.aarch64-apple-darwin.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfb75e2d0e393ff0c4b2351f2a40e4e133924a55"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "bb52f3a19c5abe47ee04f2cf7ef2b197d3c76859871d70d38607ad35c8b9bfc6"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "275e51c8ef13a06e61efc8fa8533d30e8e248db1"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "3a9dddf5331ecc2de068a625195689ed15c489a095075ce62d24d1af4c0cbcf2"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6350a64b2d1bd35a3c4ad3d41d502f09daded3fc"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "f50477e69517bc15f4a4607dd71beee187678325672120dc96090b4c4da4165b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.aarch64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19bfb0dc07040289c9eed032eeeda0c25ec06a3c"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "3c15f0e2342afacfa6acdab4c6ff749f560e294f81a7d9d8cb2c5b2ba08189ab"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.aarch64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42810ce9f5598e6b25fb8e8fb5c8e7df6ae351e9"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "c4cfaf9153ab91c94f336467566cc7daf90dacfe83d5684b127d92536676477b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b29a94b07f3475dd876d809492c32ea1003fbe99"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "f770b7565ba426a17e7e123fa9d55867994c756410cdfc4f2f83b9aa784a04f0"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bac8169cf64e51074b24c2b53a4150207aebec9"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "6a64c31bc668e060b869a5123bb1e13bcde4bc8bea234bf96f4d1b8a7f487d76"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f50a74e67c981597285d7aa308a227625e9869d9"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "154ed4c295e91044f8c7e8b366b1848fcd9125df2284738efa883706a8df7d8a"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29c8bef3266e77cdf82faf7845bbaa9d6603cc48"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "3f0bab50b474a0e1207a79401b5c8625d2c90a54afbbd9f521c8fe333fb78f88"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccdcf1d90b59ea0f8be6e21efeb9cbbb6ee3407"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "10a6ea69049dc34473225db7339ab8fafc16cd4a191c67dd58ce885bb9d3ee00"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8fa43a57d213dc40d8513e4cdb27e527643347c"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "10197ebc243a8a26ff842f8f1f938f47877e3546346b91b336d473feb024e39b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ded082996f53edc409443a67f1320ea3ffe727f"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "f149b9ecd2d67f9f547cd6553a096bfef3c65f3402a00b47453c2f8f17041d70"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f93120989d9791801fbd6e479e7124dc4b19655"
os = "windows"

    [[Graphviz.download]]
    sha256 = "4d608fa5a4f71d429c1908f00994352b97bf17a398185b161a088997c80c5372"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d35c0dbfc4f5d6dae4d213af3b4a3d88e45d7c6"
os = "windows"

    [[Graphviz.download]]
    sha256 = "883500d3c321e10874908fc82e8566cece3d9cbebb366129efb42f6e523cdfda"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.i686-w64-mingw32-cxx11.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1090f7ef2f0c022cfe7457aa2dd6ea2f22ebdda9"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "dbac6384dba1b10aa08b71665724a70e2ef226b42c047d6467f5e43b91d92249"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29ba8feaf9b3c5c8f566364f195f71cf16a66487"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "2bbbff94f3ad9572fce2b0ab1b5df5d6012a92b29bba48b429e68ce42d87a4ce"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "c370e1c3fc991c5346c0d24aa6d423645cce6369"
os = "macos"

    [[Graphviz.download]]
    sha256 = "9cfcd4b3f9a34ff31d91c48e81c4f29d098a08a71e7282e03117ada7bc51792d"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-apple-darwin.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d5a66d95716d67f5730758437e31c5bbfd2490e"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "744a4aa0812b9e91b5147f2f44a69e97e3a0d749ff8199ac52ca83912f0425b4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d537ab3e58dc1cb671e3c31453c94a7812fc041a"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1aac3145a7d9b5b5872976f5bb0bb7ef413c971d62cc808c7c102b70fe99298b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "872ce01aa15fdbcfde75db48c440d86dfbd261d4"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "bab96ff5389ea4eedefa64e14efd3d9d9a557384fa56409f39c0f922b56d4915"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30a7e122e56d824548f3f1557f3de6b13d543b2e"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "5fb52eaacfeb5ca0e347749ce4c07e5806f1652238f4669e0d3b5bc930085791"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "9b5711615ae3e951aba2561fbe8de2b814a3d65b"
os = "freebsd"

    [[Graphviz.download]]
    sha256 = "245fbc865f24435521544ff51938acd5c0a79ecd483c6472d27a1ac21393a310"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-unknown-freebsd.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "859d50a9cf12e80859afca4a2eca21a5a8438c4e"
os = "windows"

    [[Graphviz.download]]
    sha256 = "4b3f31b51153a876ab88a4fe7b52b483cb9997e9ec630c9fcf0a3381de01458c"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe953b243052d917a40d9958573bc8f76632260d"
os = "windows"

    [[Graphviz.download]]
    sha256 = "9099e229765e16c776981b632b6ecaf66c17ba59274ea09301a61d392e87b478"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+0/Graphviz.v2.50.0.x86_64-w64-mingw32-cxx11.tar.gz"
