[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b43af1cde5a89030b4f2f1c3138b70427560f2ef"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "282c28afb005235d30723b99b4eb806379de3fde6d13fc8a8ee06eec4a2912c5"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c5b4470553f6b43515da763559af96ed27ad5a5"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "5f496048462b78ce773f0a7b06c654682f9a08924f603b2411cda79a1d25822f"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6172944f50400ac656ac259c4878bbfee9d57efc"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "ed8dbbb97642bb03c7bf9921ab670c80bc56852619c7ee68782e361c7a571442"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.aarch64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f401889a081a0aabd512038d751bea7e4688f5d"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "2a7c472be91efc88e45b93060bcbedfc9e3afbb754e4bc81e98fb0f908aa8617"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.aarch64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82802b8b65050adc51137075aedc8624a131f88c"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "7b5058724f0ebb81f312474cfa08dd086bc733f6f8782f0d1f0953dc22c3c9c9"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e322feb88a5515a0201343d10afa21097ae47fed"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "b13b0e587eef98545350583798abf1e064409d10af5158aa1300eeeda716f9c9"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "775dd4c4ef91166aff04c0d277621a188e552d39"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "17b2a089f3d9e906cd13a717c3dca466db58176d870639b34941624b991347d7"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "745ab5426317c54607e0a722d5d177acec8a7719"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "13699d086ae01e76ff9dd3adcbbe3b23a4c66c96a5f142d34115a1b67f5821f0"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3f03ed2ab57ff051bcfe40ea06a84c74cb5629a"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1392630d4d22cf4bbdd2ca831b18032251b1bea20fd41c2429217d373167e4dd"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5718701c17da1b19b316a7c491d38bcd9e3fa3b"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "43a4cfe8596a42555ed374d3874dd4f95b83cce6132be1f0dc691f208ed2d86f"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99eee9cc2d44e8558d0a5c3a6482a22e7664b317"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "b62a409599f2d243cd26b11c106de1181ac463ad095fe77d9e31a0dfb7659060"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "051e90700f9ea4ef07e0a01f3c59fe7813d6615b"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "50580316a36dadefe91fe4b9cbfe401c7465daad75f344d7bbfa4e7386f8e18c"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c4a6c5b234b68b056c47430ef39f7da4479a2c9"
os = "windows"

    [[Graphviz.download]]
    sha256 = "c2bc11c7fc7a735d3e3cc0aa4341e142e9f70133e0c76f256d7b5fec3aba2dd9"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4586456083ae8d0667a333b744693d6530dd7ebd"
os = "windows"

    [[Graphviz.download]]
    sha256 = "76e0cae182ee0ccc05541ff03a07e51f7c458e62a8bdcc04ac454c421947a811"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.i686-w64-mingw32-cxx11.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddcdfe22cfd91fac3c8231112f5d0bcaf80bd518"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "24e14d6b142b46510a99fb18687ae9149539d1da7e2daa222c4651b3dd01a6f4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "845a6b41b25a4f7f6051fd173c3c500f1666112a"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "febf85bff16fd3005fc98f97e5eb4a3024974382d89cdba4c8f4a76db713fe76"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "ffcec4063cae3cfeb2fa393c189bd860a2be043d"
os = "macos"

    [[Graphviz.download]]
    sha256 = "23cd0832989e49a60a181a460eadb49a276944bc582bc7cfae42d95eeee6591c"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-apple-darwin.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cd6ed4ea1d597147a682b88b98ce3edf8accf9d"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1464d2ecbff6515b539c39180adaeb85946497295676616ab03576c2eb1dbe2b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4459f3970c13531d2e370ffa9941e3d08b00f890"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "7724216d6b72267aead68b90ef2e784e72a917c259e70f4b729dfbb350ef8725"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12ef4a0fb0b20542ed5d399a20afd8eedf4f7705"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1c23c0188f8d93c89ad9d5d4389880b4a99fab5dd5858a8c5f528f73cb74bc01"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b8bb342749febc3ce0991e588539fb08ebc608b"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "986827a96d94bb184f2271882265b69c85b18f3eb3959a3ab10f0a1bff701cc9"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "15875e23603310efaadbdb22130eba77a5fe6d96"
os = "freebsd"

    [[Graphviz.download]]
    sha256 = "76b25cf1de0b8ef313973f576848a2cf25afb1336d5f19e18bf63652e639c491"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-unknown-freebsd.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85adb246c58ed64fd2a515869ee8d694cfbeb7d7"
os = "windows"

    [[Graphviz.download]]
    sha256 = "d37de7a40a83642373f272a8dd3d0c01afe74e0b32c7208e28c8399680fb413d"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21263d61dc2fdcf7b2d2102a99e4a6cd4438f277"
os = "windows"

    [[Graphviz.download]]
    sha256 = "f7819715bf673036168d8f72834846b8324dee879e31c7d3a8dde3e317a72de8"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.49.3+1/Graphviz.v2.49.3.x86_64-w64-mingw32-cxx11.tar.gz"
