[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fac3752ea2ded153db847eade47b9f8e4f0006c6"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "dfcfaa573903fcd99568a2b727ac9b74d066c2467e8e524a475f2c8ca1ba559c"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01de994fb9e8b46a39ba4f5ada38e3067440fc7f"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "805fc8f1b890e315ddc88bb22906806dc3e76786d5bf88bbc4b12dfd23251a35"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75b0be829110528e5ba4e969192f08a737a3713a"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "57d8f610cc41038943619c88f6b3daf25864501b7ccb44572bc068439ee0dce6"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.aarch64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66c7a6fd35dbbbeaa4b503d2a8bc6621da184a38"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "9ef80f3f38cf15d391e6f5b9c8144006d3eda614db7a32af91d22b5fa6e2a1f4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.aarch64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff8ad169326afd41d46f507a960c1717f4ed1a47"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "a6a4ecd39fd91fa72abd6ea647d015bc2f1cdf3431167291c151e7c167e98caf"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8e5a5b73328de7672407f2944776e3d6fbe391a"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "8527da30ee3397fe5a0972980c085ace766e52b8d8adc8339630dfaab63d7ba3"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e32313d581b2689c43432872a743357c2058b151"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1ac5f31e9a1b835fbbd30ea019bb86e05e896d36e3b6edc96bdd124112e6596c"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2093557516f98f3e0f6258b4ce364ee2b6cc375"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "7b3199ca58e4d908776117f3246460b7151d0bdae1f52eeda5f699d546712568"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70e65402a5b810467c1489ddb8006f4cdb08d425"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "91d9389bc45bb194fbab1d1051ed2799ee4d8e5dff252bbe6fab51decdcef480"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.i686-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9952e90787261a4cdcc29cdd1eb511f6bf76ccb"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "59302f9946f409693ad77756f8d15ee9294e912ba30ad32b5dc8cfe747ee6f44"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.i686-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9c6dc847ebf265d58eedac361d65492bceecdf7"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "4da03083c9188ebf908d8c00bd79534396a70edfec2b79a61917788281c77896"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.i686-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ca21ff94b2468b6441045d189484c6e8425d991"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "d5a7016132112f99390ca30732fa0f82b5183d80cb9f2fecc16d3df126ee883b"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.i686-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a8c8c8f7b5aa90575957b8452124cf2ad017ddf"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "b59855d132e1b7375176ac3543d31ab753bd3da3fb93bff82095a52ba2a3cba9"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb4b015be2e9a0eb8b659e626ada1897f4b507f6"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "6a45ddaa434f0272ba4d97757781798177754d119e955aafe2bc91c68c1a1288"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cd9e640503417eb053e36d344f41a09da0d1a1a"
os = "macos"

    [[Graphviz.download]]
    sha256 = "27b96a86faf0494f1cb033079895ab0ebe0d7062141ceb95caf1fa89445553eb"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6457d23222d6cb27ff900ad8d7ecaa0bfb2c4332"
os = "macos"

    [[Graphviz.download]]
    sha256 = "fb528cecfdf83d9ab1143d843875371b1a7194d849ca9b1b0fa31272e679f3fc"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5c1777e84981f20e8c7680f04bf2d91b5dabc61"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "c896a5e22167c95d0a171282c554b75b7e5e19d369f476261afb4d3bf56450d5"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edb465e7f0fe4ebd11efbafb9df31084e544ac07"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "25218352547f5e7a075358482a9d79c05eec914a6bd9bfb66fae4e306edc3bb4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e25ebcddd3641520649b4edc236703bd0636c02f"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "079a2b9d5db7d784e5cce6638a5aa98a2b281a9aa324483848c67a3263a07066"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fb9f05d5f3083ab044787871499e593f48b0408"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "5f924fb96691a15767e52890b2adb0d8f1424db653384f8915b2a38e43a59253"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.42.3+1/Graphviz.v2.42.3.x86_64-linux-musl-cxx11.tar.gz"
