[[Graphviz]]
arch = "aarch64"
git-tree-sha1 = "dbc1b7f42ddb07be07d55ad976317ad027618c63"
os = "macos"

    [[Graphviz.download]]
    sha256 = "facd14a69d24874767e158ef52ceaea1954ce84db16de1527bf34efcb75ab324"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.aarch64-apple-darwin.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "621fa76ec545a1a1ea203740f0d406f88ddcc286"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "f2435114ea09ceddc4a2767537fae1c80463a2233dfa4edb8fa9cb2cfc2bf826"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7521c3a93b9d07c8e3ce6f7873b00631cb376d1e"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "97b34c2d88c2f3534d168a0450848eb6fc9e7724898f4a9bf20babaf58728b31"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3ea87ae0f3703da4b9b78b57a1d2079e0f4dd77"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "fdfbc9a2332574bac94d8431cfcfcd2cb8427f2a00b034e119da49243ddc63f0"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.aarch64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b8a45f5e627eee2b25a57fa0c29e4c7560e8d2d"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "a4aa89b5ee25566bdb2b188fef7340468340456343bbca5ff4dec23466f42bbf"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.aarch64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abc6fb2cf7163828f5ed7355e8e9cff66f9e7262"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "a23b57d722950ed09772349e609621f1a643dd7c809d81ab5afdfa3cdad92703"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baedfaef08370468072a75820c04919c1f2e9c8c"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "99ca781387b2223b0e3ff701349e7edc09f93a5deb502ee2f15ee1eb5646f48f"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e10f8b7c536062c4ffa07a121fc8948f369d007"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "1917f167374a8935e18a19fd27ece50a06df874ef46e115dcdb7f0fad9bbfd89"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Graphviz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bfda9e4528e3ebb86a36ebfe6815acf7f420f65"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "0cb3335c5c80f4b7bf54f3327096e9166eb4aadcd83304c89c9c94a518a1cee4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84239209ebc3c24509c3173fa093568f3d6138db"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "b2cbe495616e6f50346be52978567e7abf23cbfd93b70d8cfd0ac87309a5124d"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f172dfd4dbd833527358304581c6ed467fa5cf40"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "93281824e6a838909f4b75d0fb0323b8b140f22fa05c7ce1275b7eb96e2981d4"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b6c9b6968b6a30e979a1374901248f1d78d3645"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "17fbef7d9499c035679f1b58bd31eb6d798615883a9ca79bb5258d73fcea0b91"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f7c26bff3f6a21001391327151982ea199c0559"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "e3730dd4d05bca987eeee01832ea879cec6edb3195d9048bc04a890cc791ec73"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1660e4b33e20292c1d3481477ac6c67d7e33b798"
os = "windows"

    [[Graphviz.download]]
    sha256 = "0d4d6baa28ea4b41c562ff5e43e67485032074e59974c944f905c758e539a9ab"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06fb73ec375cca82fd6fc57b681bce76891d6f4e"
os = "windows"

    [[Graphviz.download]]
    sha256 = "25b75a7c81eb9fbf539f3e619dd33a9d571aeffbd798b154ff08e12268a8b3b1"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.i686-w64-mingw32-cxx11.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5b20cf6a7ba3878a906feb404cad0d3373e294f"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "d44e7fe13f185ad97e99eaf4d0c765d13af66d7904c4a417013eaf28000de7b0"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8342aad98f2692acde3f73adeda2edfc9f59f4a"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "4f2cdfd66913ae889e8d4a60915a90008ffb702a57ca2cf72ec7a9918771c3eb"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "0a0b07f40c6b4154d227ff79118e29e914ba967d"
os = "macos"

    [[Graphviz.download]]
    sha256 = "7d93093715127a8f6c8330b8fc965efd5fae16f4737af51d8cfbaa870a50b076"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-apple-darwin.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34f9172dcb3fc63568d5a8ad9e16ead515795d68"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "279c28ad3cd9ee56187cc906213061fde84a76d1ab07107ecaff4f70e1051317"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3dac23e0689782ef38c4ec77fad65e352f3b778"
libc = "glibc"
os = "linux"

    [[Graphviz.download]]
    sha256 = "94c1a7ff2d3710122c975bdf2f3d39d8592ab2487baec54c0cb61c2147f43893"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49f07d5374d65bc8ba9c16afc1e7c259b5f98db1"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "e6afcbf75e8a507a230a769d3613e1c946d1faa08e6b683844dca25aaeb0050a"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-linux-musl-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f574209d5118f92d0f2024a5a5f7e9d6831aca0f"
libc = "musl"
os = "linux"

    [[Graphviz.download]]
    sha256 = "2969a56421911606c5c94dccafbb3510dfca674ec6b85aff47c64e59cb0b665f"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-linux-musl-cxx11.tar.gz"
[[Graphviz]]
arch = "x86_64"
git-tree-sha1 = "a7d4653875ed6489dc62ad4ed0fa1194c336001c"
os = "freebsd"

    [[Graphviz.download]]
    sha256 = "e4309955900cb1cb8d3802ae4b5bf4e60dad8b31c987196ba3ea30af856912ae"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-unknown-freebsd.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0be0e4aedf5b86ea8d76c21bc0775c484d69181d"
os = "windows"

    [[Graphviz.download]]
    sha256 = "0c2b5f83db4c7b3aa0c70f77b1b89dd453af1f1a3d3dfc461117dea1633a7eef"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Graphviz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f37d1697b9fed90b6fa79f05a4a5bf0e1de6a983"
os = "windows"

    [[Graphviz.download]]
    sha256 = "37d3fdb43baa0c30a9279fbb9b4029a0b26fdb34853ccb9cfef57cf778b95282"
    url = "https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl/releases/download/Graphviz-v2.50.0+1/Graphviz.v2.50.0.x86_64-w64-mingw32-cxx11.tar.gz"
