# Autogenerated wrapper script for Graphviz_jll for i686-w64-mingw32-cxx03
export acyclic, bcomps, ccomps, circo, cluster, dijkstra, dot, dot2gxl, dot_builtins, edgepaint, fdp, gc, gml2gv, graphml2gv, gv2gml, gv2gxl, gvcolor, gvgen, gvmap, gvpack, gvpr, gxl2dot, gxl2gv, libcdt, libcgraph, libgvc, libgvpr, liblab_gamut, libpathplan, libxdot, mm2gv, neato, nop, osage, patchwork, prune, sccmap, sfdp, tred, twopi, unflatten

using Cairo_jll
using Expat_jll
using Pango_jll
JLLWrappers.@generate_wrapper_header("Graphviz")
JLLWrappers.@declare_library_product(libcdt, "libcdt-5.dll")
JLLWrappers.@declare_library_product(libcgraph, "libcgraph-6.dll")
JLLWrappers.@declare_library_product(libgvc, "libgvc-6.dll")
JLLWrappers.@declare_library_product(libgvpr, "libgvpr-2.dll")
JLLWrappers.@declare_library_product(liblab_gamut, "liblab_gamut-1.dll")
JLLWrappers.@declare_library_product(libpathplan, "libpathplan-4.dll")
JLLWrappers.@declare_library_product(libxdot, "libxdot-4.dll")
JLLWrappers.@declare_executable_product(acyclic)
JLLWrappers.@declare_executable_product(bcomps)
JLLWrappers.@declare_executable_product(ccomps)
JLLWrappers.@declare_executable_product(circo)
JLLWrappers.@declare_executable_product(cluster)
JLLWrappers.@declare_executable_product(dijkstra)
JLLWrappers.@declare_executable_product(dot)
JLLWrappers.@declare_executable_product(dot2gxl)
JLLWrappers.@declare_executable_product(dot_builtins)
JLLWrappers.@declare_executable_product(edgepaint)
JLLWrappers.@declare_executable_product(fdp)
JLLWrappers.@declare_executable_product(gc)
JLLWrappers.@declare_executable_product(gml2gv)
JLLWrappers.@declare_executable_product(graphml2gv)
JLLWrappers.@declare_executable_product(gv2gml)
JLLWrappers.@declare_executable_product(gv2gxl)
JLLWrappers.@declare_executable_product(gvcolor)
JLLWrappers.@declare_executable_product(gvgen)
JLLWrappers.@declare_executable_product(gvmap)
JLLWrappers.@declare_executable_product(gvpack)
JLLWrappers.@declare_executable_product(gvpr)
JLLWrappers.@declare_executable_product(gxl2dot)
JLLWrappers.@declare_executable_product(gxl2gv)
JLLWrappers.@declare_executable_product(mm2gv)
JLLWrappers.@declare_executable_product(neato)
JLLWrappers.@declare_executable_product(nop)
JLLWrappers.@declare_executable_product(osage)
JLLWrappers.@declare_executable_product(patchwork)
JLLWrappers.@declare_executable_product(prune)
JLLWrappers.@declare_executable_product(sccmap)
JLLWrappers.@declare_executable_product(sfdp)
JLLWrappers.@declare_executable_product(tred)
JLLWrappers.@declare_executable_product(twopi)
JLLWrappers.@declare_executable_product(unflatten)
function __init__()
    JLLWrappers.@generate_init_header(Cairo_jll, Expat_jll, Pango_jll)
    JLLWrappers.@init_library_product(
        libcdt,
        "bin\\libcdt-5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcgraph,
        "bin\\libcgraph-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgvc,
        "bin\\libgvc-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgvpr,
        "bin\\libgvpr-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblab_gamut,
        "bin\\liblab_gamut-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpathplan,
        "bin\\libpathplan-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxdot,
        "bin\\libxdot-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        acyclic,
        "bin\\acyclic.exe",
    )

    JLLWrappers.@init_executable_product(
        bcomps,
        "bin\\bcomps.exe",
    )

    JLLWrappers.@init_executable_product(
        ccomps,
        "bin\\ccomps.exe",
    )

    JLLWrappers.@init_executable_product(
        circo,
        "bin\\circo.exe",
    )

    JLLWrappers.@init_executable_product(
        cluster,
        "bin\\cluster.exe",
    )

    JLLWrappers.@init_executable_product(
        dijkstra,
        "bin\\dijkstra.exe",
    )

    JLLWrappers.@init_executable_product(
        dot,
        "bin\\dot.exe",
    )

    JLLWrappers.@init_executable_product(
        dot2gxl,
        "bin\\dot2gxl.exe",
    )

    JLLWrappers.@init_executable_product(
        dot_builtins,
        "bin\\dot_builtins.exe",
    )

    JLLWrappers.@init_executable_product(
        edgepaint,
        "bin\\edgepaint.exe",
    )

    JLLWrappers.@init_executable_product(
        fdp,
        "bin\\fdp.exe",
    )

    JLLWrappers.@init_executable_product(
        gc,
        "bin\\gc.exe",
    )

    JLLWrappers.@init_executable_product(
        gml2gv,
        "bin\\gml2gv.exe",
    )

    JLLWrappers.@init_executable_product(
        graphml2gv,
        "bin\\graphml2gv.exe",
    )

    JLLWrappers.@init_executable_product(
        gv2gml,
        "bin\\gv2gml.exe",
    )

    JLLWrappers.@init_executable_product(
        gv2gxl,
        "bin\\gv2gxl.exe",
    )

    JLLWrappers.@init_executable_product(
        gvcolor,
        "bin\\gvcolor.exe",
    )

    JLLWrappers.@init_executable_product(
        gvgen,
        "bin\\gvgen.exe",
    )

    JLLWrappers.@init_executable_product(
        gvmap,
        "bin\\gvmap.exe",
    )

    JLLWrappers.@init_executable_product(
        gvpack,
        "bin\\gvpack.exe",
    )

    JLLWrappers.@init_executable_product(
        gvpr,
        "bin\\gvpr.exe",
    )

    JLLWrappers.@init_executable_product(
        gxl2dot,
        "bin\\gxl2dot.exe",
    )

    JLLWrappers.@init_executable_product(
        gxl2gv,
        "bin\\gxl2gv.exe",
    )

    JLLWrappers.@init_executable_product(
        mm2gv,
        "bin\\mm2gv.exe",
    )

    JLLWrappers.@init_executable_product(
        neato,
        "bin\\neato.exe",
    )

    JLLWrappers.@init_executable_product(
        nop,
        "bin\\nop.exe",
    )

    JLLWrappers.@init_executable_product(
        osage,
        "bin\\osage.exe",
    )

    JLLWrappers.@init_executable_product(
        patchwork,
        "bin\\patchwork.exe",
    )

    JLLWrappers.@init_executable_product(
        prune,
        "bin\\prune.exe",
    )

    JLLWrappers.@init_executable_product(
        sccmap,
        "bin\\sccmap.exe",
    )

    JLLWrappers.@init_executable_product(
        sfdp,
        "bin\\sfdp.exe",
    )

    JLLWrappers.@init_executable_product(
        tred,
        "bin\\tred.exe",
    )

    JLLWrappers.@init_executable_product(
        twopi,
        "bin\\twopi.exe",
    )

    JLLWrappers.@init_executable_product(
        unflatten,
        "bin\\unflatten.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
